### ISSUE TITLE
[Open-source] Looking forward to open-sourced data and codebase~

### ISSUE THREAD

**Issue by Li-Qingyun** [mbzuai-oryx/GeoChat#1]
Hi, thanks for your great work of GeoChat, which makes great progress for RS community. We are looking forward to the open-sourced data and codebase ASAP. What is the schedule of the data releasing.

**Comment by LindaCh21792urch** [comment]
i have the same question too

**Comment by KjAeRsTuIsK** [comment]
Hi!, Thank you for your interest and patience, we have open sourced the code, dataset, model and evaluation benchmarks.
