### ISSUE TITLE
Problems with installation

### ISSUE THREAD

**Issue by SunShineAwayD** [mbzuai-oryx/GeoChat#18]
![image](https://github.com/mbzuai-oryx/GeoChat/assets/49228626/a800c8e5-5a67-448d-a2f0-951912bad630)

When I get to "pip install flash-attn --no-build-isolation", I get this error.
He needs CUDA 11.6 or higher
But I have CUDA 11.7 and 12.1 .
so can i get some help？

**Comment by YUQI-YANG0302** [comment]
same problem! how to fix this?

**Comment by YUQI-YANG0302** [comment]
https://zhuanlan.zhihu.com/p/1935348019592667724  fixed!
