### ISSUE TITLE
Error in geochat_demo.py

### ISSUE THREAD

**Issue by xianjiedai** [mbzuai-oryx/GeoChat#27]
Thanks for the amazing work. I am trying to explore GeoChat on various tasks and I get stuck on the demo. I would appreciate it a lot if you could help me debug the error.

<img width="1481" alt="image" src="https://github.com/mbzuai-oryx/GeoChat/assets/92470082/b1801b39-4569-4225-beca-f3573580a3cf">

<img width="1074" alt="image" src="https://github.com/mbzuai-oryx/GeoChat/assets/92470082/de4ea4f6-bb71-48e6-a8c5-644332a7174d">

There is no error message in the terminal and I have followed the instructions on readme to set up everything. (Updated to the latest and the correct version of transformers etc...)

**Comment by xianjiedai** [comment]
<img width="1158" alt="image" src="https://github.com/mbzuai-oryx/GeoChat/assets/92470082/985c9bfd-8d00-4d4a-be51-62c565084134">

I got the error message when I tried today. Could you help me debug it?

**Comment by PrashantSukkumar2** [comment]
hello, i am still getting this error, did you manage to get it resolved ?

**Comment by PGthon** [comment]
@xianjiedai  hello  have you mixed that？
