### ISSUE TITLE
evaluation about referring and grounding

### ISSUE THREAD

**Issue by Hoteryoung** [mbzuai-oryx/GeoChat#30]
Will the referring and grounding questions JSONL file for evaluation be opened?

**Comment by KjAeRsTuIsK** [comment]
Hi @Hoteryoung , the evaluation files are available at [Geochat Bench](https://huggingface.co/datasets/MBZUAI/GeoChat-Bench).

**Comment by Hoteryoung** [comment]
Thanks!
