### ISSUE TITLE
ValueError when loading huggingface MBZUAI/geochat-7B model

### ISSUE THREAD

**Issue by leihamilton** [mbzuai-oryx/GeoChat#56]
I got a ValueError about KeyError: 'geochat', when loading the model from downloaded local one. It is not in transformers' configuration map.

>
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File [~/miniforge3/envs/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py:1034](http://localhost:8889/lab/tree/~/miniforge3/envs/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py#line=1033), in AutoConfig.from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
   1033 try:
-> 1034     config_class = CONFIG_MAPPING[config_dict["model_type"]]
   1035 except KeyError:

File [~/miniforge3/envs/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py:736](http://localhost:8889/lab/tree/~/miniforge3/envs/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py#line=735), in _LazyConfigMapping.__getitem__(self, key)
    735 if key not in self._mapping:
--> 736     raise KeyError(key)
    737 value = self._mapping[key]

KeyError: 'geochat'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
Cell In[5], line 3
      1 from transformers import AutoModelForCausalLM, AutoProcessor
----> 3 geochat_model = AutoProcessor.from_pretrained(
      4     "[./model](http://localhost:8889/lab/tree/model)",
      5     local_files_only=True
      6 )

File [~/miniforge3/envs/lib/python3.10/site-packages/transformers/models/auto/processing_auto.py:299](http://localhost:8889/lab/tree/~/miniforge3/envs/lib/python3.10/site-packages/transformers/models/auto/processing_auto.py#line=298), in AutoProcessor.from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
    296 if processor_class is None:
    297     # Otherwise, load config, if it can be loaded.
    298     if not isinstance(config, PretrainedConfig):
--> 299         config = AutoConfig.from_pretrained(
    300             pretrained_model_name_or_path, trust_remote_code=trust_remote_code, **kwargs
    301         )
    303     # And check if the config contains the processor class.
    304     processor_class = getattr(config, "processor_class", None)

File [~/miniforge3/envs/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py:1036](http://localhost:8889/lab/tree/~/miniforge3/envs/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py#line=1035), in AutoConfig.from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
   1034         config_class = CONFIG_MAPPING[config_dict["model_type"]]
   1035     except KeyError:
-> 1036         raise ValueError(
   1037             f"The checkpoint you are trying to load has model type `{config_dict['model_type']}` "
   1038             "but Transformers does not recognize this architecture. This could be because of an "
   1039             "issue with the checkpoint, or because your version of Transformers is out of date."
   1040         )
   1041     return config_class.from_dict(config_dict, **unused_kwargs)
   1042 else:
   1043     # Fallback: use pattern matching on the string.
   1044     # We go from longer names to shorter names to catch roberta before bert (for instance)

ValueError: The checkpoint you are trying to load has model type `geochat` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.

**Comment by leihamilton** [comment]
Figured out it can not use huggingface load_dataset to load.

**Comment by LordZerror** [comment]
Could you please share the steps you took to resolve the error? 
I have updated the Transformers library to its latest version.

**Comment by vietvo89** [comment]
@LordZerror, Huggingface does not work at all. You have to manually download the pre-trained 7B model.
