### ISSUE TITLE
Gradio demo is not live

### ISSUE THREAD

**Issue by RubenGres** [mbzuai-oryx/GeoChat#8]
Hello!

The gradio interface linked in the readme (https://3fa767b988e4136cd8.gradio.live/) is not running

**Comment by KjAeRsTuIsK** [comment]
Hi! Thank you for your interest, you can run the demo locally using the instructions in [LoRA.md](https://github.com/mbzuai-oryx/GeoChat/blob/main/docs/LoRA.md)

**Comment by PrashantSukkumar2** [comment]
@KjAeRsTuIsK the demo is not correct, it is faulty and full of bugs,
![image](https://github.com/user-attachments/assets/59be9c5c-bf3b-4391-8883-261ddd428b1b)

please help us. thanks
